stages:
- build
- deploy

linux:
  stage: build
  script:
  - "./build.sh"
  - "mkdir linux"
  - "cp v8/out.gn/release/obj/libv8_lib{base,platform}.a linux/"
  artifacts:
    name: "v8-prebuilt-$CI_BUILD_ID"
    paths:
    - linux
    expire_in: 1 week
  tags:
  - linux
  - x64

windows:
  stage: build
  script:
  - "./build.sh"
  - "mkdir windows"
  - "cp v8/out.gn/release/obj/libv8_lib{base,platform}.lib windows/"
  artifacts:
    name: "v8-prebuilt-$CI_BUILD_ID"
    paths:
    - windows
    expire_in: 1 week
  tags:
  - windows
  - x64

macos:
  stage: build
  script:
  - "./build.sh"
  - "mkdir macos"
  - "cp v8/out.gn/release/obj/libv8_lib{base,platform}.a macos/"
  artifacts:
    name: "v8-prebuilt-$CI_BUILD_ID"
    paths:
    - macos
    expire_in: 1 week
  tags:
  - macos
  - x64
