stages:
- build
- deploy

.build_template: &build
  stage: build
  script:
  - "./build.sh"
  artifacts:
    name: "v8-prebuilt-$CI_BUILD_ID"
    paths:
    - v8-prebuilt
    - tests.out
    - tests.err
    expire_in: 1 week

linux:
  <<: *build
  tags:
  - linux
  - x64

windows:
  <<: *build
  tags:
  - windows
  - x64

macos:
  <<: *build
  tags:
  - macos
  - x64
